# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/openisms/api.proto", :syntax => :proto3) do
    add_message "io.openisms.v1.Event" do
      optional :meta, :message, 1, "io.openisms.v1.Meta"
      optional :source, :message, 2, "io.openisms.v1.SourceSystem"
      repeated :users, :message, 3, "io.openisms.v1.User"
      repeated :devices, :message, 4, "io.openisms.v1.PhysicalObject"
      repeated :repositories, :message, 7, "io.openisms.v1.Repository"
      repeated :certification, :message, 9, "io.openisms.v1.Certification"
      repeated :pentest, :message, 11, "io.openisms.v1.Pentest"
      repeated :stats, :message, 13, "io.openisms.v1.Statistics"
    end
    add_message "io.openisms.v1.Meta" do
      optional :created, :message, 1, "google.protobuf.Timestamp"
      optional :identifier, :string, 2
      optional :etag, :string, 3
    end
    add_message "io.openisms.v1.SourceSystem" do
      optional :name, :string, 1
      optional :vendor, :string, 2
      optional :url, :string, 3
      optional :logo_url, :string, 4
      optional :type, :enum, 5, "io.openisms.v1.SourceSystem.SourceType"
    end
    add_enum "io.openisms.v1.SourceSystem.SourceType" do
      value :undefined, 0
      value :identity_provider, 1
      value :source_control_management, 2
      value :cloud_provider, 3
      value :database, 4
      value :network, 5
      value :device_management, 10
      value :security_software, 11
      value :password_manager, 12
      value :communication, 20
      value :human_resources, 21
      value :content_management_system, 22
      value :ticketing, 23
      value :customer_relationship_management, 24
      value :finance, 25
      value :analytics, 26
    end
    add_message "io.openisms.v1.User" do
      optional :person, :message, 1, "io.openisms.v1.Person"
      optional :second_factor_active, :message, 5, "google.protobuf.BoolValue"
      optional :second_factor_enforced, :message, 6, "google.protobuf.BoolValue"
      optional :active, :message, 7, "google.protobuf.BoolValue"
      optional :suspended, :message, 8, "google.protobuf.BoolValue"
      optional :disabled, :message, 9, "google.protobuf.BoolValue"
      optional :deleted, :message, 10, "google.protobuf.BoolValue"
      repeated :groups, :string, 15
      repeated :privileges, :string, 16
      optional :employment, :message, 20, "io.openisms.v1.Employment"
      repeated :connected_accounts, :message, 21, "io.openisms.v1.ConnectedAccount"
      repeated :possessions, :message, 22, "io.openisms.v1.PhysicalObject"
      repeated :tags, :string, 40
    end
    add_message "io.openisms.v1.Person" do
      optional :id, :string, 1
      optional :name, :message, 2, "io.openisms.v1.Name"
      optional :primary_email, :string, 3
      repeated :other_emails, :string, 4
      optional :picture, :message, 5, "io.openisms.v1.UrlWithEtag"
      optional :company, :string, 6
      optional :created, :message, 10, "google.protobuf.Timestamp"
      optional :updated, :message, 11, "google.protobuf.Timestamp"
    end
    add_message "io.openisms.v1.Name" do
      optional :given_name, :string, 1
      optional :family_name, :string, 2
      optional :full_name, :string, 3
      optional :title, :string, 4
      optional :position, :string, 5
      optional :role, :string, 6
    end
    add_message "io.openisms.v1.UrlWithEtag" do
      optional :url, :string, 1
      optional :etag, :string, 2
      optional :last_modified, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "io.openisms.v1.Employment" do
      optional :contract, :string, 1
      optional :status, :string, 2
      optional :begin, :message, 3, "io.openisms.v1.Date"
      optional :end, :message, 4, "io.openisms.v1.Date"
    end
    add_message "io.openisms.v1.ConnectedAccount" do
      optional :app_id, :string, 1
      optional :app_name, :string, 2
      optional :app_type, :string, 3
      optional :app_url, :string, 4
      optional :user_id, :string, 5
      repeated :scopes, :string, 6
    end
    add_message "io.openisms.v1.PhysicalObject" do
      optional :type, :string, 1
      optional :name, :string, 2
      optional :manufacturer, :string, 3
      optional :vendor, :string, 4
      optional :identifier, :string, 5
      optional :serial_number, :string, 6
      optional :imei, :string, 7
      optional :meid, :string, 8
      repeated :networks, :message, 9, "io.openisms.v1.Network"
      optional :hostname, :string, 10
      repeated :user_accounts, :string, 11
      optional :os, :message, 12, "io.openisms.v1.OperatingSystem"
      optional :security, :message, 13, "io.openisms.v1.SecurityFeatures"
      repeated :profiles, :message, 14, "io.openisms.v1.Profile"
      repeated :apps, :message, 15, "io.openisms.v1.Application"
      repeated :tags, :string, 20
    end
    add_message "io.openisms.v1.SecurityFeatures" do
      optional :activation_lock, :message, 1, "google.protobuf.BoolValue"
      optional :supervised, :message, 2, "google.protobuf.BoolValue"
      optional :file_vault, :message, 3, "google.protobuf.BoolValue"
      optional :full_disk_encryption, :message, 4, "google.protobuf.BoolValue"
      optional :secure_password, :message, 5, "google.protobuf.BoolValue"
      optional :automatic_screen_lock, :message, 6, "google.protobuf.BoolValue"
      optional :screen_lock_after, :message, 7, "google.protobuf.Int32Value"
      optional :firewall_enabled, :message, 8, "google.protobuf.BoolValue"
      optional :automatic_updates, :message, 9, "google.protobuf.BoolValue"
    end
    add_message "io.openisms.v1.Network" do
      optional :name, :string, 1
      optional :type, :string, 2
      optional :mac_address, :string, 3
    end
    add_message "io.openisms.v1.OperatingSystem" do
      optional :os, :message, 1, "io.openisms.v1.OperatingSystem"
      optional :major_version, :string, 2
      optional :full_version, :string, 3
    end
    add_enum "io.openisms.v1.OperatingSystem.OperatingSystems" do
      value :undefined, 0
      value :macos, 1
      value :windows, 2
      value :linux, 3
      value :unix, 4
      value :chrome_os, 5
      value :ios, 10
      value :android, 11
      value :ros, 14
      value :other, 15
    end
    add_message "io.openisms.v1.Application" do
      optional :name, :string, 1
      optional :path, :string, 2
      optional :vendor, :string, 3
      optional :url, :string, 4
      optional :description, :string, 5
      optional :version, :string, 6
      optional :signed, :message, 7, "google.protobuf.BoolValue"
      optional :system_app, :message, 8, "google.protobuf.BoolValue"
      optional :installation_source, :string, 9
    end
    add_message "io.openisms.v1.Profile" do
      optional :name, :string, 1
      optional :identifier, :string, 2
      optional :removal_allowed, :message, 3, "google.protobuf.BoolValue"
      optional :payload_type, :string, 4
      optional :payload_identifier, :string, 5
    end
    add_message "io.openisms.v1.Date" do
      optional :year, :int32, 1
      optional :month, :int32, 2
      optional :day, :int32, 3
    end
    add_message "io.openisms.v1.Certification" do
      optional :type, :string, 1
      optional :url, :string, 2
      repeated :tags, :string, 10
    end
    add_message "io.openisms.v1.Company" do
      optional :name, :string, 1
      optional :url, :string, 2
      optional :category, :string, 3
      optional :contact, :message, 4, "io.openisms.v1.Person"
      repeated :address, :string, 5
    end
    add_message "io.openisms.v1.Pentest" do
      optional :id, :string, 1
      optional :begin, :message, 2, "io.openisms.v1.Date"
      optional :end, :message, 3, "io.openisms.v1.Date"
      optional :company, :message, 4, "io.openisms.v1.Company"
      optional :focus, :string, 5
      optional :passed, :bool, 6
      optional :result, :string, 7
      optional :url, :string, 8
      repeated :contacts, :message, 9, "io.openisms.v1.Person"
      repeated :tags, :string, 10
    end
    add_message "io.openisms.v1.Repository" do
      optional :name, :string, 1
      optional :url, :string, 2
      optional :description, :string, 3
      optional :visibility, :enum, 4, "io.openisms.v1.Visibility"
      repeated :members, :message, 5, "io.openisms.v1.Person"
      repeated :security_attributes, :string, 6
      repeated :tags, :string, 10
    end
    add_message "io.openisms.v1.Statistics" do
      optional :identifier, :string, 1
      optional :name, :string, 2
      optional :value, :int32, 3
      optional :comment, :string, 4
    end
    add_enum "io.openisms.v1.Visibility" do
      value :undefined, 0
      value :public, 1
      value :internal, 2
      value :confidential, 3
    end
  end
end

module Io
  module Openisms
    module V1
      Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Event").msgclass
      Meta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Meta").msgclass
      SourceSystem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.SourceSystem").msgclass
      SourceSystem::SourceType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.SourceSystem.SourceType").enummodule
      User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.User").msgclass
      Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Person").msgclass
      Name = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Name").msgclass
      UrlWithEtag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.UrlWithEtag").msgclass
      Employment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Employment").msgclass
      ConnectedAccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.ConnectedAccount").msgclass
      PhysicalObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.PhysicalObject").msgclass
      SecurityFeatures = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.SecurityFeatures").msgclass
      Network = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Network").msgclass
      OperatingSystem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.OperatingSystem").msgclass
      OperatingSystem::OperatingSystems = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.OperatingSystem.OperatingSystems").enummodule
      Application = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Application").msgclass
      Profile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Profile").msgclass
      Date = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Date").msgclass
      Certification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Certification").msgclass
      Company = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Company").msgclass
      Pentest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Pentest").msgclass
      Repository = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Repository").msgclass
      Statistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Statistics").msgclass
      Visibility = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.openisms.v1.Visibility").enummodule
    end
  end
end
