// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.openisms.api

@SerialVersionUID(0L)
final case class Profile(
    name: _root_.scala.Predef.String = "",
    identifier: _root_.scala.Predef.String = "",
    removalAllowed: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    payloadType: _root_.scala.Predef.String = "",
    payloadIdentifier: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Profile] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = identifier
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      if (removalAllowed.isDefined) {
        val __value = io.openisms.api.Profile._typemapper_removalAllowed.toBase(removalAllowed.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = payloadType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = payloadIdentifier
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = identifier
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      removalAllowed.foreach { __v =>
        val __m = io.openisms.api.Profile._typemapper_removalAllowed.toBase(__v)
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = payloadType
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = payloadIdentifier
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withName(__v: _root_.scala.Predef.String): Profile = copy(name = __v)
    def withIdentifier(__v: _root_.scala.Predef.String): Profile = copy(identifier = __v)
    def getRemovalAllowed: _root_.scala.Boolean = removalAllowed.getOrElse(io.openisms.api.Profile._typemapper_removalAllowed.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearRemovalAllowed: Profile = copy(removalAllowed = _root_.scala.None)
    def withRemovalAllowed(__v: _root_.scala.Boolean): Profile = copy(removalAllowed = Option(__v))
    def withPayloadType(__v: _root_.scala.Predef.String): Profile = copy(payloadType = __v)
    def withPayloadIdentifier(__v: _root_.scala.Predef.String): Profile = copy(payloadIdentifier = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = identifier
          if (__t != "") __t else null
        }
        case 3 => removalAllowed.map(io.openisms.api.Profile._typemapper_removalAllowed.toBase(_)).orNull
        case 4 => {
          val __t = payloadType
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = payloadIdentifier
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PString(identifier)
        case 3 => removalAllowed.map(io.openisms.api.Profile._typemapper_removalAllowed.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => _root_.scalapb.descriptors.PString(payloadType)
        case 5 => _root_.scalapb.descriptors.PString(payloadIdentifier)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.openisms.api.Profile.type = io.openisms.api.Profile
    // @@protoc_insertion_point(GeneratedMessage[io.openisms.v1.Profile])
}

object Profile extends scalapb.GeneratedMessageCompanion[io.openisms.api.Profile] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.openisms.api.Profile] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.openisms.api.Profile = {
    var __name: _root_.scala.Predef.String = ""
    var __identifier: _root_.scala.Predef.String = ""
    var __removalAllowed: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __payloadType: _root_.scala.Predef.String = ""
    var __payloadIdentifier: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __name = _input__.readStringRequireUtf8()
        case 18 =>
          __identifier = _input__.readStringRequireUtf8()
        case 26 =>
          __removalAllowed = Option(io.openisms.api.Profile._typemapper_removalAllowed.toCustom(__removalAllowed.map(io.openisms.api.Profile._typemapper_removalAllowed.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 34 =>
          __payloadType = _input__.readStringRequireUtf8()
        case 42 =>
          __payloadIdentifier = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.openisms.api.Profile(
        name = __name,
        identifier = __identifier,
        removalAllowed = __removalAllowed,
        payloadType = __payloadType,
        payloadIdentifier = __payloadIdentifier,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.openisms.api.Profile] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.openisms.api.Profile(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        identifier = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        removalAllowed = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.Profile._typemapper_removalAllowed.toCustom(_)),
        payloadType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        payloadIdentifier = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ApiProto.javaDescriptor.getMessageTypes().get(14)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ApiProto.scalaDescriptor.messages(14)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = com.google.protobuf.wrappers.BoolValue
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.openisms.api.Profile(
    name = "",
    identifier = "",
    removalAllowed = _root_.scala.None,
    payloadType = "",
    payloadIdentifier = ""
  )
  implicit class ProfileLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.openisms.api.Profile]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.openisms.api.Profile](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def identifier: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.identifier)((c_, f_) => c_.copy(identifier = f_))
    def removalAllowed: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getRemovalAllowed)((c_, f_) => c_.copy(removalAllowed = Option(f_)))
    def optionalRemovalAllowed: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.removalAllowed)((c_, f_) => c_.copy(removalAllowed = f_))
    def payloadType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.payloadType)((c_, f_) => c_.copy(payloadType = f_))
    def payloadIdentifier: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.payloadIdentifier)((c_, f_) => c_.copy(payloadIdentifier = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val IDENTIFIER_FIELD_NUMBER = 2
  final val REMOVAL_ALLOWED_FIELD_NUMBER = 3
  final val PAYLOAD_TYPE_FIELD_NUMBER = 4
  final val PAYLOAD_IDENTIFIER_FIELD_NUMBER = 5
  @transient
  private[api] val _typemapper_removalAllowed: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  def of(
    name: _root_.scala.Predef.String,
    identifier: _root_.scala.Predef.String,
    removalAllowed: _root_.scala.Option[_root_.scala.Boolean],
    payloadType: _root_.scala.Predef.String,
    payloadIdentifier: _root_.scala.Predef.String
  ): _root_.io.openisms.api.Profile = _root_.io.openisms.api.Profile(
    name,
    identifier,
    removalAllowed,
    payloadType,
    payloadIdentifier
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.openisms.v1.Profile])
}
