// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.openisms.api

@SerialVersionUID(0L)
final case class SecurityFeatures(
    activationLock: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    supervised: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    fileVault: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    fullDiskEncryption: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    securePassword: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    automaticScreenLock: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    screenLockAfter: _root_.scala.Option[_root_.scala.Int] = _root_.scala.None,
    firewallEnabled: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    automaticUpdates: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SecurityFeatures] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (activationLock.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_activationLock.toBase(activationLock.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (supervised.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_supervised.toBase(supervised.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (fileVault.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_fileVault.toBase(fileVault.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (fullDiskEncryption.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toBase(fullDiskEncryption.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (securePassword.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_securePassword.toBase(securePassword.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (automaticScreenLock.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toBase(automaticScreenLock.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (screenLockAfter.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toBase(screenLockAfter.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (firewallEnabled.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toBase(firewallEnabled.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (automaticUpdates.isDefined) {
        val __value = io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toBase(automaticUpdates.get)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      activationLock.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_activationLock.toBase(__v)
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      supervised.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_supervised.toBase(__v)
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      fileVault.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_fileVault.toBase(__v)
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      fullDiskEncryption.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toBase(__v)
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      securePassword.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_securePassword.toBase(__v)
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      automaticScreenLock.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toBase(__v)
        _output__.writeTag(6, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      screenLockAfter.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toBase(__v)
        _output__.writeTag(7, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      firewallEnabled.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toBase(__v)
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      automaticUpdates.foreach { __v =>
        val __m = io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toBase(__v)
        _output__.writeTag(9, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getActivationLock: _root_.scala.Boolean = activationLock.getOrElse(io.openisms.api.SecurityFeatures._typemapper_activationLock.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearActivationLock: SecurityFeatures = copy(activationLock = _root_.scala.None)
    def withActivationLock(__v: _root_.scala.Boolean): SecurityFeatures = copy(activationLock = Option(__v))
    def getSupervised: _root_.scala.Boolean = supervised.getOrElse(io.openisms.api.SecurityFeatures._typemapper_supervised.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearSupervised: SecurityFeatures = copy(supervised = _root_.scala.None)
    def withSupervised(__v: _root_.scala.Boolean): SecurityFeatures = copy(supervised = Option(__v))
    def getFileVault: _root_.scala.Boolean = fileVault.getOrElse(io.openisms.api.SecurityFeatures._typemapper_fileVault.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearFileVault: SecurityFeatures = copy(fileVault = _root_.scala.None)
    def withFileVault(__v: _root_.scala.Boolean): SecurityFeatures = copy(fileVault = Option(__v))
    def getFullDiskEncryption: _root_.scala.Boolean = fullDiskEncryption.getOrElse(io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearFullDiskEncryption: SecurityFeatures = copy(fullDiskEncryption = _root_.scala.None)
    def withFullDiskEncryption(__v: _root_.scala.Boolean): SecurityFeatures = copy(fullDiskEncryption = Option(__v))
    def getSecurePassword: _root_.scala.Boolean = securePassword.getOrElse(io.openisms.api.SecurityFeatures._typemapper_securePassword.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearSecurePassword: SecurityFeatures = copy(securePassword = _root_.scala.None)
    def withSecurePassword(__v: _root_.scala.Boolean): SecurityFeatures = copy(securePassword = Option(__v))
    def getAutomaticScreenLock: _root_.scala.Boolean = automaticScreenLock.getOrElse(io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearAutomaticScreenLock: SecurityFeatures = copy(automaticScreenLock = _root_.scala.None)
    def withAutomaticScreenLock(__v: _root_.scala.Boolean): SecurityFeatures = copy(automaticScreenLock = Option(__v))
    def getScreenLockAfter: _root_.scala.Int = screenLockAfter.getOrElse(io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toCustom(com.google.protobuf.wrappers.Int32Value.defaultInstance))
    def clearScreenLockAfter: SecurityFeatures = copy(screenLockAfter = _root_.scala.None)
    def withScreenLockAfter(__v: _root_.scala.Int): SecurityFeatures = copy(screenLockAfter = Option(__v))
    def getFirewallEnabled: _root_.scala.Boolean = firewallEnabled.getOrElse(io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearFirewallEnabled: SecurityFeatures = copy(firewallEnabled = _root_.scala.None)
    def withFirewallEnabled(__v: _root_.scala.Boolean): SecurityFeatures = copy(firewallEnabled = Option(__v))
    def getAutomaticUpdates: _root_.scala.Boolean = automaticUpdates.getOrElse(io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toCustom(com.google.protobuf.wrappers.BoolValue.defaultInstance))
    def clearAutomaticUpdates: SecurityFeatures = copy(automaticUpdates = _root_.scala.None)
    def withAutomaticUpdates(__v: _root_.scala.Boolean): SecurityFeatures = copy(automaticUpdates = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => activationLock.map(io.openisms.api.SecurityFeatures._typemapper_activationLock.toBase(_)).orNull
        case 2 => supervised.map(io.openisms.api.SecurityFeatures._typemapper_supervised.toBase(_)).orNull
        case 3 => fileVault.map(io.openisms.api.SecurityFeatures._typemapper_fileVault.toBase(_)).orNull
        case 4 => fullDiskEncryption.map(io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toBase(_)).orNull
        case 5 => securePassword.map(io.openisms.api.SecurityFeatures._typemapper_securePassword.toBase(_)).orNull
        case 6 => automaticScreenLock.map(io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toBase(_)).orNull
        case 7 => screenLockAfter.map(io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toBase(_)).orNull
        case 8 => firewallEnabled.map(io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toBase(_)).orNull
        case 9 => automaticUpdates.map(io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toBase(_)).orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => activationLock.map(io.openisms.api.SecurityFeatures._typemapper_activationLock.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => supervised.map(io.openisms.api.SecurityFeatures._typemapper_supervised.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => fileVault.map(io.openisms.api.SecurityFeatures._typemapper_fileVault.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => fullDiskEncryption.map(io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 5 => securePassword.map(io.openisms.api.SecurityFeatures._typemapper_securePassword.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 6 => automaticScreenLock.map(io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 7 => screenLockAfter.map(io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 8 => firewallEnabled.map(io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 9 => automaticUpdates.map(io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toBase(_).toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.openisms.api.SecurityFeatures.type = io.openisms.api.SecurityFeatures
    // @@protoc_insertion_point(GeneratedMessage[io.openisms.v1.SecurityFeatures])
}

object SecurityFeatures extends scalapb.GeneratedMessageCompanion[io.openisms.api.SecurityFeatures] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.openisms.api.SecurityFeatures] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.openisms.api.SecurityFeatures = {
    var __activationLock: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __supervised: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __fileVault: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __fullDiskEncryption: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __securePassword: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __automaticScreenLock: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __screenLockAfter: _root_.scala.Option[_root_.scala.Int] = _root_.scala.None
    var __firewallEnabled: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var __automaticUpdates: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __activationLock = Option(io.openisms.api.SecurityFeatures._typemapper_activationLock.toCustom(__activationLock.map(io.openisms.api.SecurityFeatures._typemapper_activationLock.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 18 =>
          __supervised = Option(io.openisms.api.SecurityFeatures._typemapper_supervised.toCustom(__supervised.map(io.openisms.api.SecurityFeatures._typemapper_supervised.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 26 =>
          __fileVault = Option(io.openisms.api.SecurityFeatures._typemapper_fileVault.toCustom(__fileVault.map(io.openisms.api.SecurityFeatures._typemapper_fileVault.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 34 =>
          __fullDiskEncryption = Option(io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toCustom(__fullDiskEncryption.map(io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 42 =>
          __securePassword = Option(io.openisms.api.SecurityFeatures._typemapper_securePassword.toCustom(__securePassword.map(io.openisms.api.SecurityFeatures._typemapper_securePassword.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 50 =>
          __automaticScreenLock = Option(io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toCustom(__automaticScreenLock.map(io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 58 =>
          __screenLockAfter = Option(io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toCustom(__screenLockAfter.map(io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.Int32Value](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 66 =>
          __firewallEnabled = Option(io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toCustom(__firewallEnabled.map(io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case 74 =>
          __automaticUpdates = Option(io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toCustom(__automaticUpdates.map(io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toBase(_)).fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.wrappers.BoolValue](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _))))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.openisms.api.SecurityFeatures(
        activationLock = __activationLock,
        supervised = __supervised,
        fileVault = __fileVault,
        fullDiskEncryption = __fullDiskEncryption,
        securePassword = __securePassword,
        automaticScreenLock = __automaticScreenLock,
        screenLockAfter = __screenLockAfter,
        firewallEnabled = __firewallEnabled,
        automaticUpdates = __automaticUpdates,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.openisms.api.SecurityFeatures] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.openisms.api.SecurityFeatures(
        activationLock = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_activationLock.toCustom(_)),
        supervised = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_supervised.toCustom(_)),
        fileVault = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_fileVault.toCustom(_)),
        fullDiskEncryption = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_fullDiskEncryption.toCustom(_)),
        securePassword = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_securePassword.toCustom(_)),
        automaticScreenLock = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_automaticScreenLock.toCustom(_)),
        screenLockAfter = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.Int32Value]]).map(io.openisms.api.SecurityFeatures._typemapper_screenLockAfter.toCustom(_)),
        firewallEnabled = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_firewallEnabled.toCustom(_)),
        automaticUpdates = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.wrappers.BoolValue]]).map(io.openisms.api.SecurityFeatures._typemapper_automaticUpdates.toCustom(_))
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ApiProto.javaDescriptor.getMessageTypes().get(10)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ApiProto.scalaDescriptor.messages(10)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.google.protobuf.wrappers.BoolValue
      case 2 => __out = com.google.protobuf.wrappers.BoolValue
      case 3 => __out = com.google.protobuf.wrappers.BoolValue
      case 4 => __out = com.google.protobuf.wrappers.BoolValue
      case 5 => __out = com.google.protobuf.wrappers.BoolValue
      case 6 => __out = com.google.protobuf.wrappers.BoolValue
      case 7 => __out = com.google.protobuf.wrappers.Int32Value
      case 8 => __out = com.google.protobuf.wrappers.BoolValue
      case 9 => __out = com.google.protobuf.wrappers.BoolValue
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.openisms.api.SecurityFeatures(
    activationLock = _root_.scala.None,
    supervised = _root_.scala.None,
    fileVault = _root_.scala.None,
    fullDiskEncryption = _root_.scala.None,
    securePassword = _root_.scala.None,
    automaticScreenLock = _root_.scala.None,
    screenLockAfter = _root_.scala.None,
    firewallEnabled = _root_.scala.None,
    automaticUpdates = _root_.scala.None
  )
  implicit class SecurityFeaturesLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.openisms.api.SecurityFeatures]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.openisms.api.SecurityFeatures](_l) {
    def activationLock: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getActivationLock)((c_, f_) => c_.copy(activationLock = Option(f_)))
    def optionalActivationLock: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.activationLock)((c_, f_) => c_.copy(activationLock = f_))
    def supervised: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getSupervised)((c_, f_) => c_.copy(supervised = Option(f_)))
    def optionalSupervised: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.supervised)((c_, f_) => c_.copy(supervised = f_))
    def fileVault: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getFileVault)((c_, f_) => c_.copy(fileVault = Option(f_)))
    def optionalFileVault: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.fileVault)((c_, f_) => c_.copy(fileVault = f_))
    def fullDiskEncryption: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getFullDiskEncryption)((c_, f_) => c_.copy(fullDiskEncryption = Option(f_)))
    def optionalFullDiskEncryption: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.fullDiskEncryption)((c_, f_) => c_.copy(fullDiskEncryption = f_))
    def securePassword: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getSecurePassword)((c_, f_) => c_.copy(securePassword = Option(f_)))
    def optionalSecurePassword: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.securePassword)((c_, f_) => c_.copy(securePassword = f_))
    def automaticScreenLock: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getAutomaticScreenLock)((c_, f_) => c_.copy(automaticScreenLock = Option(f_)))
    def optionalAutomaticScreenLock: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.automaticScreenLock)((c_, f_) => c_.copy(automaticScreenLock = f_))
    def screenLockAfter: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.getScreenLockAfter)((c_, f_) => c_.copy(screenLockAfter = Option(f_)))
    def optionalScreenLockAfter: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Int]] = field(_.screenLockAfter)((c_, f_) => c_.copy(screenLockAfter = f_))
    def firewallEnabled: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getFirewallEnabled)((c_, f_) => c_.copy(firewallEnabled = Option(f_)))
    def optionalFirewallEnabled: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.firewallEnabled)((c_, f_) => c_.copy(firewallEnabled = f_))
    def automaticUpdates: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getAutomaticUpdates)((c_, f_) => c_.copy(automaticUpdates = Option(f_)))
    def optionalAutomaticUpdates: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.automaticUpdates)((c_, f_) => c_.copy(automaticUpdates = f_))
  }
  final val ACTIVATION_LOCK_FIELD_NUMBER = 1
  final val SUPERVISED_FIELD_NUMBER = 2
  final val FILE_VAULT_FIELD_NUMBER = 3
  final val FULL_DISK_ENCRYPTION_FIELD_NUMBER = 4
  final val SECURE_PASSWORD_FIELD_NUMBER = 5
  final val AUTOMATIC_SCREEN_LOCK_FIELD_NUMBER = 6
  final val SCREEN_LOCK_AFTER_FIELD_NUMBER = 7
  final val FIREWALL_ENABLED_FIELD_NUMBER = 8
  final val AUTOMATIC_UPDATES_FIELD_NUMBER = 9
  @transient
  private[api] val _typemapper_activationLock: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  @transient
  private[api] val _typemapper_supervised: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  @transient
  private[api] val _typemapper_fileVault: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  @transient
  private[api] val _typemapper_fullDiskEncryption: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  @transient
  private[api] val _typemapper_securePassword: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  @transient
  private[api] val _typemapper_automaticScreenLock: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  @transient
  private[api] val _typemapper_screenLockAfter: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.Int32Value, _root_.scala.Int] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.Int32Value, _root_.scala.Int]]
  @transient
  private[api] val _typemapper_firewallEnabled: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  @transient
  private[api] val _typemapper_automaticUpdates: _root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean] = implicitly[_root_.scalapb.TypeMapper[com.google.protobuf.wrappers.BoolValue, _root_.scala.Boolean]]
  def of(
    activationLock: _root_.scala.Option[_root_.scala.Boolean],
    supervised: _root_.scala.Option[_root_.scala.Boolean],
    fileVault: _root_.scala.Option[_root_.scala.Boolean],
    fullDiskEncryption: _root_.scala.Option[_root_.scala.Boolean],
    securePassword: _root_.scala.Option[_root_.scala.Boolean],
    automaticScreenLock: _root_.scala.Option[_root_.scala.Boolean],
    screenLockAfter: _root_.scala.Option[_root_.scala.Int],
    firewallEnabled: _root_.scala.Option[_root_.scala.Boolean],
    automaticUpdates: _root_.scala.Option[_root_.scala.Boolean]
  ): _root_.io.openisms.api.SecurityFeatures = _root_.io.openisms.api.SecurityFeatures(
    activationLock,
    supervised,
    fileVault,
    fullDiskEncryption,
    securePassword,
    automaticScreenLock,
    screenLockAfter,
    firewallEnabled,
    automaticUpdates
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.openisms.v1.SecurityFeatures])
}
