// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.openisms.api

@SerialVersionUID(0L)
final case class SourceSystem(
    name: _root_.scala.Predef.String = "",
    vendor: _root_.scala.Predef.String = "",
    url: _root_.scala.Predef.String = "",
    logoUrl: _root_.scala.Predef.String = "",
    `type`: io.openisms.api.SourceSystem.SourceType = io.openisms.api.SourceSystem.SourceType.undefined,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SourceSystem] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = vendor
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = url
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = logoUrl
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = `type`.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = vendor
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = url
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = logoUrl
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = `type`.value
        if (__v != 0) {
          _output__.writeEnum(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withName(__v: _root_.scala.Predef.String): SourceSystem = copy(name = __v)
    def withVendor(__v: _root_.scala.Predef.String): SourceSystem = copy(vendor = __v)
    def withUrl(__v: _root_.scala.Predef.String): SourceSystem = copy(url = __v)
    def withLogoUrl(__v: _root_.scala.Predef.String): SourceSystem = copy(logoUrl = __v)
    def withType(__v: io.openisms.api.SourceSystem.SourceType): SourceSystem = copy(`type` = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = vendor
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = url
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = logoUrl
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = `type`.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PString(vendor)
        case 3 => _root_.scalapb.descriptors.PString(url)
        case 4 => _root_.scalapb.descriptors.PString(logoUrl)
        case 5 => _root_.scalapb.descriptors.PEnum(`type`.scalaValueDescriptor)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.openisms.api.SourceSystem.type = io.openisms.api.SourceSystem
    // @@protoc_insertion_point(GeneratedMessage[io.openisms.v1.SourceSystem])
}

object SourceSystem extends scalapb.GeneratedMessageCompanion[io.openisms.api.SourceSystem] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.openisms.api.SourceSystem] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.openisms.api.SourceSystem = {
    var __name: _root_.scala.Predef.String = ""
    var __vendor: _root_.scala.Predef.String = ""
    var __url: _root_.scala.Predef.String = ""
    var __logoUrl: _root_.scala.Predef.String = ""
    var __type: io.openisms.api.SourceSystem.SourceType = io.openisms.api.SourceSystem.SourceType.undefined
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __name = _input__.readStringRequireUtf8()
        case 18 =>
          __vendor = _input__.readStringRequireUtf8()
        case 26 =>
          __url = _input__.readStringRequireUtf8()
        case 34 =>
          __logoUrl = _input__.readStringRequireUtf8()
        case 40 =>
          __type = io.openisms.api.SourceSystem.SourceType.fromValue(_input__.readEnum())
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.openisms.api.SourceSystem(
        name = __name,
        vendor = __vendor,
        url = __url,
        logoUrl = __logoUrl,
        `type` = __type,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.openisms.api.SourceSystem] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.openisms.api.SourceSystem(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        vendor = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        url = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        logoUrl = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        `type` = io.openisms.api.SourceSystem.SourceType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(io.openisms.api.SourceSystem.SourceType.undefined.scalaValueDescriptor).number)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ApiProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ApiProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 5 => io.openisms.api.SourceSystem.SourceType
    }
  }
  lazy val defaultInstance = io.openisms.api.SourceSystem(
    name = "",
    vendor = "",
    url = "",
    logoUrl = "",
    `type` = io.openisms.api.SourceSystem.SourceType.undefined
  )
  sealed abstract class SourceType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
    type EnumType = SourceType
    def isundefined: _root_.scala.Boolean = false
    def isidentityprovider: _root_.scala.Boolean = false
    def issourcecontrolmanagement: _root_.scala.Boolean = false
    def iscloudprovider: _root_.scala.Boolean = false
    def isdatabase: _root_.scala.Boolean = false
    def isnetwork: _root_.scala.Boolean = false
    def isdevicemanagement: _root_.scala.Boolean = false
    def issecuritysoftware: _root_.scala.Boolean = false
    def ispasswordmanager: _root_.scala.Boolean = false
    def iscommunication: _root_.scala.Boolean = false
    def ishumanresources: _root_.scala.Boolean = false
    def iscontentmanagementsystem: _root_.scala.Boolean = false
    def isticketing: _root_.scala.Boolean = false
    def iscustomerrelationshipmanagement: _root_.scala.Boolean = false
    def isfinance: _root_.scala.Boolean = false
    def isanalytics: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[SourceType] = io.openisms.api.SourceSystem.SourceType
    final def asRecognized: _root_.scala.Option[io.openisms.api.SourceSystem.SourceType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[io.openisms.api.SourceSystem.SourceType.Recognized])
  }
  
  object SourceType extends _root_.scalapb.GeneratedEnumCompanion[SourceType] {
    sealed trait Recognized extends SourceType
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[SourceType] = this
    
    @SerialVersionUID(0L)
    case object undefined extends SourceType(0) with SourceType.Recognized {
      val index = 0
      val name = "undefined"
      override def isundefined: _root_.scala.Boolean = true
    }
    
    /** Infrastructure
      * IdP, IAM, Google Workspace, Okta, Identity Management, Cloud Directory, Active Directory, Access Management, SAML
      */
    @SerialVersionUID(0L)
    case object identity_provider extends SourceType(1) with SourceType.Recognized {
      val index = 1
      val name = "identity_provider"
      override def isidentityprovider: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object source_control_management extends SourceType(2) with SourceType.Recognized {
      val index = 2
      val name = "source_control_management"
      override def issourcecontrolmanagement: _root_.scala.Boolean = true
    }
    
    /** AWS, Google Cloud, Azure, Hetzner, OVH
      */
    @SerialVersionUID(0L)
    case object cloud_provider extends SourceType(3) with SourceType.Recognized {
      val index = 3
      val name = "cloud_provider"
      override def iscloudprovider: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object database extends SourceType(4) with SourceType.Recognized {
      val index = 4
      val name = "database"
      override def isdatabase: _root_.scala.Boolean = true
    }
    
    /** Tailscale, Wireguard, VPN, Cloudflare
      */
    @SerialVersionUID(0L)
    case object network extends SourceType(5) with SourceType.Recognized {
      val index = 5
      val name = "network"
      override def isnetwork: _root_.scala.Boolean = true
    }
    
    /** Devices &amp; Security, connected to laptops
      * jamf, SimpleMDM
      */
    @SerialVersionUID(0L)
    case object device_management extends SourceType(10) with SourceType.Recognized {
      val index = 6
      val name = "device_management"
      override def isdevicemanagement: _root_.scala.Boolean = true
    }
    
    /** Anti-virus
      */
    @SerialVersionUID(0L)
    case object security_software extends SourceType(11) with SourceType.Recognized {
      val index = 7
      val name = "security_software"
      override def issecuritysoftware: _root_.scala.Boolean = true
    }
    
    /** MFA, 1Password
      */
    @SerialVersionUID(0L)
    case object password_manager extends SourceType(12) with SourceType.Recognized {
      val index = 8
      val name = "password_manager"
      override def ispasswordmanager: _root_.scala.Boolean = true
    }
    
    /** Tools &amp; SaaS
      * Slack, E-Mail
      */
    @SerialVersionUID(0L)
    case object communication extends SourceType(20) with SourceType.Recognized {
      val index = 9
      val name = "communication"
      override def iscommunication: _root_.scala.Boolean = true
    }
    
    /** HR, Personio, BambooHR
      */
    @SerialVersionUID(0L)
    case object human_resources extends SourceType(21) with SourceType.Recognized {
      val index = 10
      val name = "human_resources"
      override def ishumanresources: _root_.scala.Boolean = true
    }
    
    /** CMS, Notion, Confluence, WordPress
      */
    @SerialVersionUID(0L)
    case object content_management_system extends SourceType(22) with SourceType.Recognized {
      val index = 11
      val name = "content_management_system"
      override def iscontentmanagementsystem: _root_.scala.Boolean = true
    }
    
    /** Jira, Trello, Asana, Monday.com, airfocus
      */
    @SerialVersionUID(0L)
    case object ticketing extends SourceType(23) with SourceType.Recognized {
      val index = 12
      val name = "ticketing"
      override def isticketing: _root_.scala.Boolean = true
    }
    
    /** CRM
      */
    @SerialVersionUID(0L)
    case object customer_relationship_management extends SourceType(24) with SourceType.Recognized {
      val index = 13
      val name = "customer_relationship_management"
      override def iscustomerrelationshipmanagement: _root_.scala.Boolean = true
    }
    
    /** Stripe, invoice handling
      */
    @SerialVersionUID(0L)
    case object finance extends SourceType(25) with SourceType.Recognized {
      val index = 14
      val name = "finance"
      override def isfinance: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object analytics extends SourceType(26) with SourceType.Recognized {
      val index = 15
      val name = "analytics"
      override def isanalytics: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends SourceType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
    lazy val values = scala.collection.immutable.Seq(undefined, identity_provider, source_control_management, cloud_provider, database, network, device_management, security_software, password_manager, communication, human_resources, content_management_system, ticketing, customer_relationship_management, finance, analytics)
    def fromValue(__value: _root_.scala.Int): SourceType = __value match {
      case 0 => undefined
      case 1 => identity_provider
      case 2 => source_control_management
      case 3 => cloud_provider
      case 4 => database
      case 5 => network
      case 10 => device_management
      case 11 => security_software
      case 12 => password_manager
      case 20 => communication
      case 21 => human_resources
      case 22 => content_management_system
      case 23 => ticketing
      case 24 => customer_relationship_management
      case 25 => finance
      case 26 => analytics
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = io.openisms.api.SourceSystem.javaDescriptor.getEnumTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = io.openisms.api.SourceSystem.scalaDescriptor.enums(0)
  }
  implicit class SourceSystemLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.openisms.api.SourceSystem]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.openisms.api.SourceSystem](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def vendor: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.vendor)((c_, f_) => c_.copy(vendor = f_))
    def url: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.url)((c_, f_) => c_.copy(url = f_))
    def logoUrl: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.logoUrl)((c_, f_) => c_.copy(logoUrl = f_))
    def `type`: _root_.scalapb.lenses.Lens[UpperPB, io.openisms.api.SourceSystem.SourceType] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val VENDOR_FIELD_NUMBER = 2
  final val URL_FIELD_NUMBER = 3
  final val LOGO_URL_FIELD_NUMBER = 4
  final val TYPE_FIELD_NUMBER = 5
  def of(
    name: _root_.scala.Predef.String,
    vendor: _root_.scala.Predef.String,
    url: _root_.scala.Predef.String,
    logoUrl: _root_.scala.Predef.String,
    `type`: io.openisms.api.SourceSystem.SourceType
  ): _root_.io.openisms.api.SourceSystem = _root_.io.openisms.api.SourceSystem(
    name,
    vendor,
    url,
    logoUrl,
    `type`
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.openisms.v1.SourceSystem])
}
