<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

namespace Io\Openisms\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.openisms.v1.Application</code>
 */
class Application extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>string vendor = 3;</code>
     */
    protected $vendor = '';
    /**
     * Generated from protobuf field <code>string url = 4;</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>string description = 5;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string version = 6;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue signed = 7;</code>
     */
    protected $signed = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue system_app = 8;</code>
     */
    protected $system_app = null;
    /**
     * App Store; homebrew; MDM
     *
     * Generated from protobuf field <code>string installation_source = 9;</code>
     */
    protected $installation_source = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $path
     *     @type string $vendor
     *     @type string $url
     *     @type string $description
     *     @type string $version
     *     @type \Google\Protobuf\BoolValue $signed
     *     @type \Google\Protobuf\BoolValue $system_app
     *     @type string $installation_source
     *           App Store; homebrew; MDM
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Openisms\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vendor = 3;</code>
     * @return string
     */
    public function getVendor()
    {
        return $this->vendor;
    }

    /**
     * Generated from protobuf field <code>string vendor = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVendor($var)
    {
        GPBUtil::checkString($var, True);
        $this->vendor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 6;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue signed = 7;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getSigned()
    {
        return $this->signed;
    }

    public function hasSigned()
    {
        return isset($this->signed);
    }

    public function clearSigned()
    {
        unset($this->signed);
    }

    /**
     * Returns the unboxed value from <code>getSigned()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue signed = 7;</code>
     * @return bool|null
     */
    public function getSignedUnwrapped()
    {
        return $this->readWrapperValue("signed");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue signed = 7;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setSigned($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->signed = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue signed = 7;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setSignedUnwrapped($var)
    {
        $this->writeWrapperValue("signed", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue system_app = 8;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getSystemApp()
    {
        return $this->system_app;
    }

    public function hasSystemApp()
    {
        return isset($this->system_app);
    }

    public function clearSystemApp()
    {
        unset($this->system_app);
    }

    /**
     * Returns the unboxed value from <code>getSystemApp()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue system_app = 8;</code>
     * @return bool|null
     */
    public function getSystemAppUnwrapped()
    {
        return $this->readWrapperValue("system_app");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue system_app = 8;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setSystemApp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->system_app = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue system_app = 8;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setSystemAppUnwrapped($var)
    {
        $this->writeWrapperValue("system_app", $var);
        return $this;}

    /**
     * App Store; homebrew; MDM
     *
     * Generated from protobuf field <code>string installation_source = 9;</code>
     * @return string
     */
    public function getInstallationSource()
    {
        return $this->installation_source;
    }

    /**
     * App Store; homebrew; MDM
     *
     * Generated from protobuf field <code>string installation_source = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setInstallationSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->installation_source = $var;

        return $this;
    }

}

