<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

namespace Io\Openisms\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.openisms.v1.ConnectedAccount</code>
 */
class ConnectedAccount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string app_id = 1;</code>
     */
    protected $app_id = '';
    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     */
    protected $app_name = '';
    /**
     * Generated from protobuf field <code>string app_type = 3;</code>
     */
    protected $app_type = '';
    /**
     * Generated from protobuf field <code>string app_url = 4;</code>
     */
    protected $app_url = '';
    /**
     * Generated from protobuf field <code>string user_id = 5;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>repeated string scopes = 6;</code>
     */
    private $scopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app_id
     *     @type string $app_name
     *     @type string $app_type
     *     @type string $app_url
     *     @type string $user_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $scopes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Openisms\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string app_id = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>string app_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->app_name;
    }

    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_type = 3;</code>
     * @return string
     */
    public function getAppType()
    {
        return $this->app_type;
    }

    /**
     * Generated from protobuf field <code>string app_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAppType($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_url = 4;</code>
     * @return string
     */
    public function getAppUrl()
    {
        return $this->app_url;
    }

    /**
     * Generated from protobuf field <code>string app_url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAppUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string scopes = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * Generated from protobuf field <code>repeated string scopes = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scopes = $arr;

        return $this;
    }

}

