<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

namespace Io\Openisms\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.openisms.v1.PhysicalObject</code>
 */
class PhysicalObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string manufacturer = 3;</code>
     */
    protected $manufacturer = '';
    /**
     * Generated from protobuf field <code>string vendor = 4;</code>
     */
    protected $vendor = '';
    /**
     * company-internal
     *
     * Generated from protobuf field <code>string identifier = 5;</code>
     */
    protected $identifier = '';
    /**
     * Generated from protobuf field <code>string serial_number = 6;</code>
     */
    protected $serial_number = '';
    /**
     * Generated from protobuf field <code>string imei = 7;</code>
     */
    protected $imei = '';
    /**
     * Generated from protobuf field <code>string meid = 8;</code>
     */
    protected $meid = '';
    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Network networks = 9;</code>
     */
    private $networks;
    /**
     * Generated from protobuf field <code>string hostname = 10;</code>
     */
    protected $hostname = '';
    /**
     * Generated from protobuf field <code>repeated string user_accounts = 11;</code>
     */
    private $user_accounts;
    /**
     * Generated from protobuf field <code>.io.openisms.v1.OperatingSystem os = 12;</code>
     */
    protected $os = null;
    /**
     * Generated from protobuf field <code>.io.openisms.v1.SecurityFeatures security = 13;</code>
     */
    protected $security = null;
    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Profile profiles = 14;</code>
     */
    private $profiles;
    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Application apps = 15;</code>
     */
    private $apps;
    /**
     * Generated from protobuf field <code>repeated string tags = 20;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $name
     *     @type string $manufacturer
     *     @type string $vendor
     *     @type string $identifier
     *           company-internal
     *     @type string $serial_number
     *     @type string $imei
     *     @type string $meid
     *     @type \Io\Openisms\V1\Network[]|\Google\Protobuf\Internal\RepeatedField $networks
     *     @type string $hostname
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $user_accounts
     *     @type \Io\Openisms\V1\OperatingSystem $os
     *     @type \Io\Openisms\V1\SecurityFeatures $security
     *     @type \Io\Openisms\V1\Profile[]|\Google\Protobuf\Internal\RepeatedField $profiles
     *     @type \Io\Openisms\V1\Application[]|\Google\Protobuf\Internal\RepeatedField $apps
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Openisms\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string manufacturer = 3;</code>
     * @return string
     */
    public function getManufacturer()
    {
        return $this->manufacturer;
    }

    /**
     * Generated from protobuf field <code>string manufacturer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setManufacturer($var)
    {
        GPBUtil::checkString($var, True);
        $this->manufacturer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vendor = 4;</code>
     * @return string
     */
    public function getVendor()
    {
        return $this->vendor;
    }

    /**
     * Generated from protobuf field <code>string vendor = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVendor($var)
    {
        GPBUtil::checkString($var, True);
        $this->vendor = $var;

        return $this;
    }

    /**
     * company-internal
     *
     * Generated from protobuf field <code>string identifier = 5;</code>
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * company-internal
     *
     * Generated from protobuf field <code>string identifier = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serial_number = 6;</code>
     * @return string
     */
    public function getSerialNumber()
    {
        return $this->serial_number;
    }

    /**
     * Generated from protobuf field <code>string serial_number = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imei = 7;</code>
     * @return string
     */
    public function getImei()
    {
        return $this->imei;
    }

    /**
     * Generated from protobuf field <code>string imei = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setImei($var)
    {
        GPBUtil::checkString($var, True);
        $this->imei = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string meid = 8;</code>
     * @return string
     */
    public function getMeid()
    {
        return $this->meid;
    }

    /**
     * Generated from protobuf field <code>string meid = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMeid($var)
    {
        GPBUtil::checkString($var, True);
        $this->meid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Network networks = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetworks()
    {
        return $this->networks;
    }

    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Network networks = 9;</code>
     * @param \Io\Openisms\V1\Network[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Openisms\V1\Network::class);
        $this->networks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hostname = 10;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string user_accounts = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserAccounts()
    {
        return $this->user_accounts;
    }

    /**
     * Generated from protobuf field <code>repeated string user_accounts = 11;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserAccounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_accounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.OperatingSystem os = 12;</code>
     * @return \Io\Openisms\V1\OperatingSystem|null
     */
    public function getOs()
    {
        return $this->os;
    }

    public function hasOs()
    {
        return isset($this->os);
    }

    public function clearOs()
    {
        unset($this->os);
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.OperatingSystem os = 12;</code>
     * @param \Io\Openisms\V1\OperatingSystem $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkMessage($var, \Io\Openisms\V1\OperatingSystem::class);
        $this->os = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.SecurityFeatures security = 13;</code>
     * @return \Io\Openisms\V1\SecurityFeatures|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.SecurityFeatures security = 13;</code>
     * @param \Io\Openisms\V1\SecurityFeatures $var
     * @return $this
     */
    public function setSecurity($var)
    {
        GPBUtil::checkMessage($var, \Io\Openisms\V1\SecurityFeatures::class);
        $this->security = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Profile profiles = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProfiles()
    {
        return $this->profiles;
    }

    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Profile profiles = 14;</code>
     * @param \Io\Openisms\V1\Profile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProfiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Openisms\V1\Profile::class);
        $this->profiles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Application apps = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApps()
    {
        return $this->apps;
    }

    /**
     * Generated from protobuf field <code>repeated .io.openisms.v1.Application apps = 15;</code>
     * @param \Io\Openisms\V1\Application[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Openisms\V1\Application::class);
        $this->apps = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 20;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

