<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

namespace Io\Openisms\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.openisms.v1.SecurityFeatures</code>
 */
class SecurityFeatures extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     */
    protected $activation_lock = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue supervised = 2;</code>
     */
    protected $supervised = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue file_vault = 3;</code>
     */
    protected $file_vault = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     */
    protected $full_disk_encryption = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue secure_password = 5;</code>
     */
    protected $secure_password = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     */
    protected $automatic_screen_lock = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     */
    protected $screen_lock_after = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     */
    protected $firewall_enabled = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     */
    protected $automatic_updates = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\BoolValue $activation_lock
     *     @type \Google\Protobuf\BoolValue $supervised
     *     @type \Google\Protobuf\BoolValue $file_vault
     *     @type \Google\Protobuf\BoolValue $full_disk_encryption
     *     @type \Google\Protobuf\BoolValue $secure_password
     *     @type \Google\Protobuf\BoolValue $automatic_screen_lock
     *     @type \Google\Protobuf\Int32Value $screen_lock_after
     *     @type \Google\Protobuf\BoolValue $firewall_enabled
     *     @type \Google\Protobuf\BoolValue $automatic_updates
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Openisms\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getActivationLock()
    {
        return $this->activation_lock;
    }

    public function hasActivationLock()
    {
        return isset($this->activation_lock);
    }

    public function clearActivationLock()
    {
        unset($this->activation_lock);
    }

    /**
     * Returns the unboxed value from <code>getActivationLock()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     * @return bool|null
     */
    public function getActivationLockUnwrapped()
    {
        return $this->readWrapperValue("activation_lock");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setActivationLock($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->activation_lock = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setActivationLockUnwrapped($var)
    {
        $this->writeWrapperValue("activation_lock", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue supervised = 2;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getSupervised()
    {
        return $this->supervised;
    }

    public function hasSupervised()
    {
        return isset($this->supervised);
    }

    public function clearSupervised()
    {
        unset($this->supervised);
    }

    /**
     * Returns the unboxed value from <code>getSupervised()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue supervised = 2;</code>
     * @return bool|null
     */
    public function getSupervisedUnwrapped()
    {
        return $this->readWrapperValue("supervised");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue supervised = 2;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setSupervised($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->supervised = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue supervised = 2;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setSupervisedUnwrapped($var)
    {
        $this->writeWrapperValue("supervised", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue file_vault = 3;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getFileVault()
    {
        return $this->file_vault;
    }

    public function hasFileVault()
    {
        return isset($this->file_vault);
    }

    public function clearFileVault()
    {
        unset($this->file_vault);
    }

    /**
     * Returns the unboxed value from <code>getFileVault()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue file_vault = 3;</code>
     * @return bool|null
     */
    public function getFileVaultUnwrapped()
    {
        return $this->readWrapperValue("file_vault");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue file_vault = 3;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setFileVault($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->file_vault = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue file_vault = 3;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setFileVaultUnwrapped($var)
    {
        $this->writeWrapperValue("file_vault", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getFullDiskEncryption()
    {
        return $this->full_disk_encryption;
    }

    public function hasFullDiskEncryption()
    {
        return isset($this->full_disk_encryption);
    }

    public function clearFullDiskEncryption()
    {
        unset($this->full_disk_encryption);
    }

    /**
     * Returns the unboxed value from <code>getFullDiskEncryption()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     * @return bool|null
     */
    public function getFullDiskEncryptionUnwrapped()
    {
        return $this->readWrapperValue("full_disk_encryption");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setFullDiskEncryption($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->full_disk_encryption = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setFullDiskEncryptionUnwrapped($var)
    {
        $this->writeWrapperValue("full_disk_encryption", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue secure_password = 5;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getSecurePassword()
    {
        return $this->secure_password;
    }

    public function hasSecurePassword()
    {
        return isset($this->secure_password);
    }

    public function clearSecurePassword()
    {
        unset($this->secure_password);
    }

    /**
     * Returns the unboxed value from <code>getSecurePassword()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue secure_password = 5;</code>
     * @return bool|null
     */
    public function getSecurePasswordUnwrapped()
    {
        return $this->readWrapperValue("secure_password");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue secure_password = 5;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setSecurePassword($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->secure_password = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue secure_password = 5;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setSecurePasswordUnwrapped($var)
    {
        $this->writeWrapperValue("secure_password", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getAutomaticScreenLock()
    {
        return $this->automatic_screen_lock;
    }

    public function hasAutomaticScreenLock()
    {
        return isset($this->automatic_screen_lock);
    }

    public function clearAutomaticScreenLock()
    {
        unset($this->automatic_screen_lock);
    }

    /**
     * Returns the unboxed value from <code>getAutomaticScreenLock()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     * @return bool|null
     */
    public function getAutomaticScreenLockUnwrapped()
    {
        return $this->readWrapperValue("automatic_screen_lock");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setAutomaticScreenLock($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->automatic_screen_lock = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setAutomaticScreenLockUnwrapped($var)
    {
        $this->writeWrapperValue("automatic_screen_lock", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getScreenLockAfter()
    {
        return $this->screen_lock_after;
    }

    public function hasScreenLockAfter()
    {
        return isset($this->screen_lock_after);
    }

    public function clearScreenLockAfter()
    {
        unset($this->screen_lock_after);
    }

    /**
     * Returns the unboxed value from <code>getScreenLockAfter()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     * @return int|null
     */
    public function getScreenLockAfterUnwrapped()
    {
        return $this->readWrapperValue("screen_lock_after");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setScreenLockAfter($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->screen_lock_after = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     * @param int|null $var
     * @return $this
     */
    public function setScreenLockAfterUnwrapped($var)
    {
        $this->writeWrapperValue("screen_lock_after", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getFirewallEnabled()
    {
        return $this->firewall_enabled;
    }

    public function hasFirewallEnabled()
    {
        return isset($this->firewall_enabled);
    }

    public function clearFirewallEnabled()
    {
        unset($this->firewall_enabled);
    }

    /**
     * Returns the unboxed value from <code>getFirewallEnabled()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     * @return bool|null
     */
    public function getFirewallEnabledUnwrapped()
    {
        return $this->readWrapperValue("firewall_enabled");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setFirewallEnabled($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->firewall_enabled = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setFirewallEnabledUnwrapped($var)
    {
        $this->writeWrapperValue("firewall_enabled", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getAutomaticUpdates()
    {
        return $this->automatic_updates;
    }

    public function hasAutomaticUpdates()
    {
        return isset($this->automatic_updates);
    }

    public function clearAutomaticUpdates()
    {
        unset($this->automatic_updates);
    }

    /**
     * Returns the unboxed value from <code>getAutomaticUpdates()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     * @return bool|null
     */
    public function getAutomaticUpdatesUnwrapped()
    {
        return $this->readWrapperValue("automatic_updates");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setAutomaticUpdates($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->automatic_updates = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setAutomaticUpdatesUnwrapped($var)
    {
        $this->writeWrapperValue("automatic_updates", $var);
        return $this;}

}

