<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

namespace Io\Openisms\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.openisms.v1.Statistics</code>
 */
class Statistics extends \Google\Protobuf\Internal\Message
{
    /**
     * accounts:num_users, device_management:num_30day_desktop_linux_managed_devices
     *
     * Generated from protobuf field <code>string identifier = 1;</code>
     */
    protected $identifier = '';
    /**
     * Number of users
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 42
     *
     * Generated from protobuf field <code>int32 value = 3;</code>
     */
    protected $value = 0;
    /**
     * "Does not include suspended users"
     *
     * Generated from protobuf field <code>string comment = 4;</code>
     */
    protected $comment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $identifier
     *           accounts:num_users, device_management:num_30day_desktop_linux_managed_devices
     *     @type string $name
     *           Number of users
     *     @type int $value
     *           42
     *     @type string $comment
     *           "Does not include suspended users"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Openisms\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * accounts:num_users, device_management:num_30day_desktop_linux_managed_devices
     *
     * Generated from protobuf field <code>string identifier = 1;</code>
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * accounts:num_users, device_management:num_30day_desktop_linux_managed_devices
     *
     * Generated from protobuf field <code>string identifier = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Number of users
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Number of users
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 42
     *
     * Generated from protobuf field <code>int32 value = 3;</code>
     * @return int
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * 42
     *
     * Generated from protobuf field <code>int32 value = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkInt32($var);
        $this->value = $var;

        return $this;
    }

    /**
     * "Does not include suspended users"
     *
     * Generated from protobuf field <code>string comment = 4;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * "Does not include suspended users"
     *
     * Generated from protobuf field <code>string comment = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

}

