<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

namespace Io\Openisms\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.openisms.v1.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.openisms.v1.Person person = 1;</code>
     */
    protected $person = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_active = 5;</code>
     */
    protected $second_factor_active = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_enforced = 6;</code>
     */
    protected $second_factor_enforced = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue active = 7;</code>
     */
    protected $active = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue suspended = 8;</code>
     */
    protected $suspended = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue disabled = 9;</code>
     */
    protected $disabled = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue deleted = 10;</code>
     */
    protected $deleted = null;
    /**
     * Generated from protobuf field <code>repeated string groups = 15;</code>
     */
    private $groups;
    /**
     * Generated from protobuf field <code>repeated string privileges = 16;</code>
     */
    private $privileges;
    /**
     * Generated from protobuf field <code>.io.openisms.v1.Employment employment = 20;</code>
     */
    protected $employment = null;
    /**
     * via SSO, SAML, OIDC
     *
     * Generated from protobuf field <code>repeated .io.openisms.v1.ConnectedAccount connected_accounts = 21;</code>
     */
    private $connected_accounts;
    /**
     * Laptop, Phone, Adaptor
     *
     * Generated from protobuf field <code>repeated .io.openisms.v1.PhysicalObject possessions = 22;</code>
     */
    private $possessions;
    /**
     * Generated from protobuf field <code>repeated string tags = 40;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Openisms\V1\Person $person
     *     @type \Google\Protobuf\BoolValue $second_factor_active
     *     @type \Google\Protobuf\BoolValue $second_factor_enforced
     *     @type \Google\Protobuf\BoolValue $active
     *     @type \Google\Protobuf\BoolValue $suspended
     *     @type \Google\Protobuf\BoolValue $disabled
     *     @type \Google\Protobuf\BoolValue $deleted
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $groups
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $privileges
     *     @type \Io\Openisms\V1\Employment $employment
     *     @type \Io\Openisms\V1\ConnectedAccount[]|\Google\Protobuf\Internal\RepeatedField $connected_accounts
     *           via SSO, SAML, OIDC
     *     @type \Io\Openisms\V1\PhysicalObject[]|\Google\Protobuf\Internal\RepeatedField $possessions
     *           Laptop, Phone, Adaptor
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Openisms\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.Person person = 1;</code>
     * @return \Io\Openisms\V1\Person|null
     */
    public function getPerson()
    {
        return $this->person;
    }

    public function hasPerson()
    {
        return isset($this->person);
    }

    public function clearPerson()
    {
        unset($this->person);
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.Person person = 1;</code>
     * @param \Io\Openisms\V1\Person $var
     * @return $this
     */
    public function setPerson($var)
    {
        GPBUtil::checkMessage($var, \Io\Openisms\V1\Person::class);
        $this->person = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_active = 5;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getSecondFactorActive()
    {
        return $this->second_factor_active;
    }

    public function hasSecondFactorActive()
    {
        return isset($this->second_factor_active);
    }

    public function clearSecondFactorActive()
    {
        unset($this->second_factor_active);
    }

    /**
     * Returns the unboxed value from <code>getSecondFactorActive()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_active = 5;</code>
     * @return bool|null
     */
    public function getSecondFactorActiveUnwrapped()
    {
        return $this->readWrapperValue("second_factor_active");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_active = 5;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setSecondFactorActive($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->second_factor_active = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_active = 5;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setSecondFactorActiveUnwrapped($var)
    {
        $this->writeWrapperValue("second_factor_active", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_enforced = 6;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getSecondFactorEnforced()
    {
        return $this->second_factor_enforced;
    }

    public function hasSecondFactorEnforced()
    {
        return isset($this->second_factor_enforced);
    }

    public function clearSecondFactorEnforced()
    {
        unset($this->second_factor_enforced);
    }

    /**
     * Returns the unboxed value from <code>getSecondFactorEnforced()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_enforced = 6;</code>
     * @return bool|null
     */
    public function getSecondFactorEnforcedUnwrapped()
    {
        return $this->readWrapperValue("second_factor_enforced");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_enforced = 6;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setSecondFactorEnforced($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->second_factor_enforced = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue second_factor_enforced = 6;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setSecondFactorEnforcedUnwrapped($var)
    {
        $this->writeWrapperValue("second_factor_enforced", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue active = 7;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getActive()
    {
        return $this->active;
    }

    public function hasActive()
    {
        return isset($this->active);
    }

    public function clearActive()
    {
        unset($this->active);
    }

    /**
     * Returns the unboxed value from <code>getActive()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue active = 7;</code>
     * @return bool|null
     */
    public function getActiveUnwrapped()
    {
        return $this->readWrapperValue("active");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue active = 7;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->active = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue active = 7;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setActiveUnwrapped($var)
    {
        $this->writeWrapperValue("active", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue suspended = 8;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getSuspended()
    {
        return $this->suspended;
    }

    public function hasSuspended()
    {
        return isset($this->suspended);
    }

    public function clearSuspended()
    {
        unset($this->suspended);
    }

    /**
     * Returns the unboxed value from <code>getSuspended()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue suspended = 8;</code>
     * @return bool|null
     */
    public function getSuspendedUnwrapped()
    {
        return $this->readWrapperValue("suspended");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue suspended = 8;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setSuspended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->suspended = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue suspended = 8;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setSuspendedUnwrapped($var)
    {
        $this->writeWrapperValue("suspended", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue disabled = 9;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    public function hasDisabled()
    {
        return isset($this->disabled);
    }

    public function clearDisabled()
    {
        unset($this->disabled);
    }

    /**
     * Returns the unboxed value from <code>getDisabled()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue disabled = 9;</code>
     * @return bool|null
     */
    public function getDisabledUnwrapped()
    {
        return $this->readWrapperValue("disabled");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue disabled = 9;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->disabled = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue disabled = 9;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setDisabledUnwrapped($var)
    {
        $this->writeWrapperValue("disabled", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue deleted = 10;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    public function hasDeleted()
    {
        return isset($this->deleted);
    }

    public function clearDeleted()
    {
        unset($this->deleted);
    }

    /**
     * Returns the unboxed value from <code>getDeleted()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue deleted = 10;</code>
     * @return bool|null
     */
    public function getDeletedUnwrapped()
    {
        return $this->readWrapperValue("deleted");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue deleted = 10;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->deleted = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue deleted = 10;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setDeletedUnwrapped($var)
    {
        $this->writeWrapperValue("deleted", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>repeated string groups = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Generated from protobuf field <code>repeated string groups = 15;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->groups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string privileges = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrivileges()
    {
        return $this->privileges;
    }

    /**
     * Generated from protobuf field <code>repeated string privileges = 16;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrivileges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->privileges = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.Employment employment = 20;</code>
     * @return \Io\Openisms\V1\Employment|null
     */
    public function getEmployment()
    {
        return $this->employment;
    }

    public function hasEmployment()
    {
        return isset($this->employment);
    }

    public function clearEmployment()
    {
        unset($this->employment);
    }

    /**
     * Generated from protobuf field <code>.io.openisms.v1.Employment employment = 20;</code>
     * @param \Io\Openisms\V1\Employment $var
     * @return $this
     */
    public function setEmployment($var)
    {
        GPBUtil::checkMessage($var, \Io\Openisms\V1\Employment::class);
        $this->employment = $var;

        return $this;
    }

    /**
     * via SSO, SAML, OIDC
     *
     * Generated from protobuf field <code>repeated .io.openisms.v1.ConnectedAccount connected_accounts = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConnectedAccounts()
    {
        return $this->connected_accounts;
    }

    /**
     * via SSO, SAML, OIDC
     *
     * Generated from protobuf field <code>repeated .io.openisms.v1.ConnectedAccount connected_accounts = 21;</code>
     * @param \Io\Openisms\V1\ConnectedAccount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConnectedAccounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Openisms\V1\ConnectedAccount::class);
        $this->connected_accounts = $arr;

        return $this;
    }

    /**
     * Laptop, Phone, Adaptor
     *
     * Generated from protobuf field <code>repeated .io.openisms.v1.PhysicalObject possessions = 22;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPossessions()
    {
        return $this->possessions;
    }

    /**
     * Laptop, Phone, Adaptor
     *
     * Generated from protobuf field <code>repeated .io.openisms.v1.PhysicalObject possessions = 22;</code>
     * @param \Io\Openisms\V1\PhysicalObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPossessions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Openisms\V1\PhysicalObject::class);
        $this->possessions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 40;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 40;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

