<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/openisms/api.proto

namespace Io\Openisms\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>io.openisms.v1.Visibility</code>
 */
class Visibility
{
    /**
     * Generated from protobuf enum <code>undefined = 0;</code>
     */
    const undefined = 0;
    /**
     * Generated from protobuf enum <code>public = 1;</code>
     */
    const PBpublic = 1;
    /**
     * private
     *
     * Generated from protobuf enum <code>internal = 2;</code>
     */
    const internal = 2;
    /**
     * Generated from protobuf enum <code>confidential = 3;</code>
     */
    const confidential = 3;

    private static $valueToName = [
        self::undefined => 'undefined',
        self::PBpublic => 'PBpublic',
        self::internal => 'internal',
        self::confidential => 'confidential',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

