//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: io/openisms/api.proto

package io.openisms;

@kotlin.jvm.JvmName("-initializeconnectedAccount")
public inline fun connectedAccount(block: io.openisms.ConnectedAccountKt.Dsl.() -> kotlin.Unit): io.openisms.Api.ConnectedAccount =
  io.openisms.ConnectedAccountKt.Dsl._create(io.openisms.Api.ConnectedAccount.newBuilder()).apply { block() }._build()
public object ConnectedAccountKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.openisms.Api.ConnectedAccount.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.openisms.Api.ConnectedAccount.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.openisms.Api.ConnectedAccount = _builder.build()

    /**
     * <code>string app_id = 1;</code>
     */
    public var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * <code>string app_id = 1;</code>
     */
    public fun clearAppId() {
      _builder.clearAppId()
    }

    /**
     * <code>string app_name = 2;</code>
     */
    public var appName: kotlin.String
      @JvmName("getAppName")
      get() = _builder.getAppName()
      @JvmName("setAppName")
      set(value) {
        _builder.setAppName(value)
      }
    /**
     * <code>string app_name = 2;</code>
     */
    public fun clearAppName() {
      _builder.clearAppName()
    }

    /**
     * <code>string app_type = 3;</code>
     */
    public var appType: kotlin.String
      @JvmName("getAppType")
      get() = _builder.getAppType()
      @JvmName("setAppType")
      set(value) {
        _builder.setAppType(value)
      }
    /**
     * <code>string app_type = 3;</code>
     */
    public fun clearAppType() {
      _builder.clearAppType()
    }

    /**
     * <code>string app_url = 4;</code>
     */
    public var appUrl: kotlin.String
      @JvmName("getAppUrl")
      get() = _builder.getAppUrl()
      @JvmName("setAppUrl")
      set(value) {
        _builder.setAppUrl(value)
      }
    /**
     * <code>string app_url = 4;</code>
     */
    public fun clearAppUrl() {
      _builder.clearAppUrl()
    }

    /**
     * <code>string user_id = 5;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 5;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ScopesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string scopes = 6;</code>
     * @return A list containing the scopes.
     */
    public val scopes: com.google.protobuf.kotlin.DslList<kotlin.String, ScopesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getScopesList()
      )
    /**
     * <code>repeated string scopes = 6;</code>
     * @param value The scopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addScopes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ScopesProxy>.add(value: kotlin.String) {
      _builder.addScopes(value)
    }
    /**
     * <code>repeated string scopes = 6;</code>
     * @param value The scopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignScopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ScopesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string scopes = 6;</code>
     * @param values The scopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllScopes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ScopesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllScopes(values)
    }
    /**
     * <code>repeated string scopes = 6;</code>
     * @param values The scopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllScopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ScopesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string scopes = 6;</code>
     * @param index The index to set the value at.
     * @param value The scopes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setScopes")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ScopesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setScopes(index, value)
    }/**
     * <code>repeated string scopes = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearScopes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ScopesProxy>.clear() {
      _builder.clearScopes()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun io.openisms.Api.ConnectedAccount.copy(block: io.openisms.ConnectedAccountKt.Dsl.() -> kotlin.Unit): io.openisms.Api.ConnectedAccount =
  io.openisms.ConnectedAccountKt.Dsl._create(this.toBuilder()).apply { block() }._build()

