//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: io/openisms/api.proto

package io.openisms;

@kotlin.jvm.JvmName("-initializemeta")
public inline fun meta(block: io.openisms.MetaKt.Dsl.() -> kotlin.Unit): io.openisms.Api.Meta =
  io.openisms.MetaKt.Dsl._create(io.openisms.Api.Meta.newBuilder()).apply { block() }._build()
public object MetaKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.openisms.Api.Meta.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.openisms.Api.Meta.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.openisms.Api.Meta = _builder.build()

    /**
     * <code>.google.protobuf.Timestamp created = 1;</code>
     */
    public var created: com.google.protobuf.Timestamp
      @JvmName("getCreated")
      get() = _builder.getCreated()
      @JvmName("setCreated")
      set(value) {
        _builder.setCreated(value)
      }
    /**
     * <code>.google.protobuf.Timestamp created = 1;</code>
     */
    public fun clearCreated() {
      _builder.clearCreated()
    }
    /**
     * <code>.google.protobuf.Timestamp created = 1;</code>
     * @return Whether the created field is set.
     */
    public fun hasCreated(): kotlin.Boolean {
      return _builder.hasCreated()
    }

    /**
     * <code>string identifier = 2;</code>
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.getIdentifier()
      @JvmName("setIdentifier")
      set(value) {
        _builder.setIdentifier(value)
      }
    /**
     * <code>string identifier = 2;</code>
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * <code>string etag = 3;</code>
     */
    public var etag: kotlin.String
      @JvmName("getEtag")
      get() = _builder.getEtag()
      @JvmName("setEtag")
      set(value) {
        _builder.setEtag(value)
      }
    /**
     * <code>string etag = 3;</code>
     */
    public fun clearEtag() {
      _builder.clearEtag()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.openisms.Api.Meta.copy(block: io.openisms.MetaKt.Dsl.() -> kotlin.Unit): io.openisms.Api.Meta =
  io.openisms.MetaKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val io.openisms.Api.MetaOrBuilder.createdOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCreated()) getCreated() else null

