//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: io/openisms/api.proto

package io.openisms;

@kotlin.jvm.JvmName("-initializeprofile")
public inline fun profile(block: io.openisms.ProfileKt.Dsl.() -> kotlin.Unit): io.openisms.Api.Profile =
  io.openisms.ProfileKt.Dsl._create(io.openisms.Api.Profile.newBuilder()).apply { block() }._build()
public object ProfileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.openisms.Api.Profile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.openisms.Api.Profile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.openisms.Api.Profile = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>string identifier = 2;</code>
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.getIdentifier()
      @JvmName("setIdentifier")
      set(value) {
        _builder.setIdentifier(value)
      }
    /**
     * <code>string identifier = 2;</code>
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * <code>.google.protobuf.BoolValue removal_allowed = 3;</code>
     */
    public var removalAllowed: com.google.protobuf.BoolValue
      @JvmName("getRemovalAllowed")
      get() = _builder.getRemovalAllowed()
      @JvmName("setRemovalAllowed")
      set(value) {
        _builder.setRemovalAllowed(value)
      }
    /**
     * <code>.google.protobuf.BoolValue removal_allowed = 3;</code>
     */
    public fun clearRemovalAllowed() {
      _builder.clearRemovalAllowed()
    }
    /**
     * <code>.google.protobuf.BoolValue removal_allowed = 3;</code>
     * @return Whether the removalAllowed field is set.
     */
    public fun hasRemovalAllowed(): kotlin.Boolean {
      return _builder.hasRemovalAllowed()
    }

    /**
     * <code>string payload_type = 4;</code>
     */
    public var payloadType: kotlin.String
      @JvmName("getPayloadType")
      get() = _builder.getPayloadType()
      @JvmName("setPayloadType")
      set(value) {
        _builder.setPayloadType(value)
      }
    /**
     * <code>string payload_type = 4;</code>
     */
    public fun clearPayloadType() {
      _builder.clearPayloadType()
    }

    /**
     * <code>string payload_identifier = 5;</code>
     */
    public var payloadIdentifier: kotlin.String
      @JvmName("getPayloadIdentifier")
      get() = _builder.getPayloadIdentifier()
      @JvmName("setPayloadIdentifier")
      set(value) {
        _builder.setPayloadIdentifier(value)
      }
    /**
     * <code>string payload_identifier = 5;</code>
     */
    public fun clearPayloadIdentifier() {
      _builder.clearPayloadIdentifier()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.openisms.Api.Profile.copy(block: io.openisms.ProfileKt.Dsl.() -> kotlin.Unit): io.openisms.Api.Profile =
  io.openisms.ProfileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val io.openisms.Api.ProfileOrBuilder.removalAllowedOrNull: com.google.protobuf.BoolValue?
  get() = if (hasRemovalAllowed()) getRemovalAllowed() else null

