//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: io/openisms/api.proto

package io.openisms;

@kotlin.jvm.JvmName("-initializesecurityFeatures")
public inline fun securityFeatures(block: io.openisms.SecurityFeaturesKt.Dsl.() -> kotlin.Unit): io.openisms.Api.SecurityFeatures =
  io.openisms.SecurityFeaturesKt.Dsl._create(io.openisms.Api.SecurityFeatures.newBuilder()).apply { block() }._build()
public object SecurityFeaturesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.openisms.Api.SecurityFeatures.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.openisms.Api.SecurityFeatures.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.openisms.Api.SecurityFeatures = _builder.build()

    /**
     * <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     */
    public var activationLock: com.google.protobuf.BoolValue
      @JvmName("getActivationLock")
      get() = _builder.getActivationLock()
      @JvmName("setActivationLock")
      set(value) {
        _builder.setActivationLock(value)
      }
    /**
     * <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     */
    public fun clearActivationLock() {
      _builder.clearActivationLock()
    }
    /**
     * <code>.google.protobuf.BoolValue activation_lock = 1;</code>
     * @return Whether the activationLock field is set.
     */
    public fun hasActivationLock(): kotlin.Boolean {
      return _builder.hasActivationLock()
    }

    /**
     * <code>.google.protobuf.BoolValue supervised = 2;</code>
     */
    public var supervised: com.google.protobuf.BoolValue
      @JvmName("getSupervised")
      get() = _builder.getSupervised()
      @JvmName("setSupervised")
      set(value) {
        _builder.setSupervised(value)
      }
    /**
     * <code>.google.protobuf.BoolValue supervised = 2;</code>
     */
    public fun clearSupervised() {
      _builder.clearSupervised()
    }
    /**
     * <code>.google.protobuf.BoolValue supervised = 2;</code>
     * @return Whether the supervised field is set.
     */
    public fun hasSupervised(): kotlin.Boolean {
      return _builder.hasSupervised()
    }

    /**
     * <code>.google.protobuf.BoolValue file_vault = 3;</code>
     */
    public var fileVault: com.google.protobuf.BoolValue
      @JvmName("getFileVault")
      get() = _builder.getFileVault()
      @JvmName("setFileVault")
      set(value) {
        _builder.setFileVault(value)
      }
    /**
     * <code>.google.protobuf.BoolValue file_vault = 3;</code>
     */
    public fun clearFileVault() {
      _builder.clearFileVault()
    }
    /**
     * <code>.google.protobuf.BoolValue file_vault = 3;</code>
     * @return Whether the fileVault field is set.
     */
    public fun hasFileVault(): kotlin.Boolean {
      return _builder.hasFileVault()
    }

    /**
     * <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     */
    public var fullDiskEncryption: com.google.protobuf.BoolValue
      @JvmName("getFullDiskEncryption")
      get() = _builder.getFullDiskEncryption()
      @JvmName("setFullDiskEncryption")
      set(value) {
        _builder.setFullDiskEncryption(value)
      }
    /**
     * <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     */
    public fun clearFullDiskEncryption() {
      _builder.clearFullDiskEncryption()
    }
    /**
     * <code>.google.protobuf.BoolValue full_disk_encryption = 4;</code>
     * @return Whether the fullDiskEncryption field is set.
     */
    public fun hasFullDiskEncryption(): kotlin.Boolean {
      return _builder.hasFullDiskEncryption()
    }

    /**
     * <code>.google.protobuf.BoolValue secure_password = 5;</code>
     */
    public var securePassword: com.google.protobuf.BoolValue
      @JvmName("getSecurePassword")
      get() = _builder.getSecurePassword()
      @JvmName("setSecurePassword")
      set(value) {
        _builder.setSecurePassword(value)
      }
    /**
     * <code>.google.protobuf.BoolValue secure_password = 5;</code>
     */
    public fun clearSecurePassword() {
      _builder.clearSecurePassword()
    }
    /**
     * <code>.google.protobuf.BoolValue secure_password = 5;</code>
     * @return Whether the securePassword field is set.
     */
    public fun hasSecurePassword(): kotlin.Boolean {
      return _builder.hasSecurePassword()
    }

    /**
     * <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     */
    public var automaticScreenLock: com.google.protobuf.BoolValue
      @JvmName("getAutomaticScreenLock")
      get() = _builder.getAutomaticScreenLock()
      @JvmName("setAutomaticScreenLock")
      set(value) {
        _builder.setAutomaticScreenLock(value)
      }
    /**
     * <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     */
    public fun clearAutomaticScreenLock() {
      _builder.clearAutomaticScreenLock()
    }
    /**
     * <code>.google.protobuf.BoolValue automatic_screen_lock = 6;</code>
     * @return Whether the automaticScreenLock field is set.
     */
    public fun hasAutomaticScreenLock(): kotlin.Boolean {
      return _builder.hasAutomaticScreenLock()
    }

    /**
     * <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     */
    public var screenLockAfter: com.google.protobuf.Int32Value
      @JvmName("getScreenLockAfter")
      get() = _builder.getScreenLockAfter()
      @JvmName("setScreenLockAfter")
      set(value) {
        _builder.setScreenLockAfter(value)
      }
    /**
     * <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     */
    public fun clearScreenLockAfter() {
      _builder.clearScreenLockAfter()
    }
    /**
     * <code>.google.protobuf.Int32Value screen_lock_after = 7;</code>
     * @return Whether the screenLockAfter field is set.
     */
    public fun hasScreenLockAfter(): kotlin.Boolean {
      return _builder.hasScreenLockAfter()
    }

    /**
     * <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     */
    public var firewallEnabled: com.google.protobuf.BoolValue
      @JvmName("getFirewallEnabled")
      get() = _builder.getFirewallEnabled()
      @JvmName("setFirewallEnabled")
      set(value) {
        _builder.setFirewallEnabled(value)
      }
    /**
     * <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     */
    public fun clearFirewallEnabled() {
      _builder.clearFirewallEnabled()
    }
    /**
     * <code>.google.protobuf.BoolValue firewall_enabled = 8;</code>
     * @return Whether the firewallEnabled field is set.
     */
    public fun hasFirewallEnabled(): kotlin.Boolean {
      return _builder.hasFirewallEnabled()
    }

    /**
     * <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     */
    public var automaticUpdates: com.google.protobuf.BoolValue
      @JvmName("getAutomaticUpdates")
      get() = _builder.getAutomaticUpdates()
      @JvmName("setAutomaticUpdates")
      set(value) {
        _builder.setAutomaticUpdates(value)
      }
    /**
     * <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     */
    public fun clearAutomaticUpdates() {
      _builder.clearAutomaticUpdates()
    }
    /**
     * <code>.google.protobuf.BoolValue automatic_updates = 9;</code>
     * @return Whether the automaticUpdates field is set.
     */
    public fun hasAutomaticUpdates(): kotlin.Boolean {
      return _builder.hasAutomaticUpdates()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.openisms.Api.SecurityFeatures.copy(block: io.openisms.SecurityFeaturesKt.Dsl.() -> kotlin.Unit): io.openisms.Api.SecurityFeatures =
  io.openisms.SecurityFeaturesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val io.openisms.Api.SecurityFeaturesOrBuilder.activationLockOrNull: com.google.protobuf.BoolValue?
  get() = if (hasActivationLock()) getActivationLock() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.supervisedOrNull: com.google.protobuf.BoolValue?
  get() = if (hasSupervised()) getSupervised() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.fileVaultOrNull: com.google.protobuf.BoolValue?
  get() = if (hasFileVault()) getFileVault() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.fullDiskEncryptionOrNull: com.google.protobuf.BoolValue?
  get() = if (hasFullDiskEncryption()) getFullDiskEncryption() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.securePasswordOrNull: com.google.protobuf.BoolValue?
  get() = if (hasSecurePassword()) getSecurePassword() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.automaticScreenLockOrNull: com.google.protobuf.BoolValue?
  get() = if (hasAutomaticScreenLock()) getAutomaticScreenLock() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.screenLockAfterOrNull: com.google.protobuf.Int32Value?
  get() = if (hasScreenLockAfter()) getScreenLockAfter() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.firewallEnabledOrNull: com.google.protobuf.BoolValue?
  get() = if (hasFirewallEnabled()) getFirewallEnabled() else null

val io.openisms.Api.SecurityFeaturesOrBuilder.automaticUpdatesOrNull: com.google.protobuf.BoolValue?
  get() = if (hasAutomaticUpdates()) getAutomaticUpdates() else null

