// source: io/openisms/api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.io.openisms.v1.OperatingSystem');
goog.provide('proto.io.openisms.v1.OperatingSystem.OperatingSystems');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.openisms.v1.OperatingSystem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.openisms.v1.OperatingSystem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.openisms.v1.OperatingSystem.displayName = 'proto.io.openisms.v1.OperatingSystem';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.openisms.v1.OperatingSystem.prototype.toObject = function(opt_includeInstance) {
  return proto.io.openisms.v1.OperatingSystem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.openisms.v1.OperatingSystem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.openisms.v1.OperatingSystem.toObject = function(includeInstance, msg) {
  var f, obj = {
    os: jspb.Message.getFieldWithDefault(msg, 1, 0),
    majorVersion: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fullVersion: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.openisms.v1.OperatingSystem}
 */
proto.io.openisms.v1.OperatingSystem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.openisms.v1.OperatingSystem;
  return proto.io.openisms.v1.OperatingSystem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.openisms.v1.OperatingSystem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.openisms.v1.OperatingSystem}
 */
proto.io.openisms.v1.OperatingSystem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.io.openisms.v1.OperatingSystem.OperatingSystems} */ (reader.readEnum());
      msg.setOs(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMajorVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFullVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.openisms.v1.OperatingSystem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.openisms.v1.OperatingSystem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.openisms.v1.OperatingSystem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.openisms.v1.OperatingSystem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOs();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMajorVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFullVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.io.openisms.v1.OperatingSystem.OperatingSystems = {
  UNDEFINED: 0,
  MACOS: 1,
  WINDOWS: 2,
  LINUX: 3,
  UNIX: 4,
  CHROME_OS: 5,
  IOS: 10,
  ANDROID: 11,
  ROS: 14,
  OTHER: 15
};

/**
 * optional OperatingSystems os = 1;
 * @return {!proto.io.openisms.v1.OperatingSystem.OperatingSystems}
 */
proto.io.openisms.v1.OperatingSystem.prototype.getOs = function() {
  return /** @type {!proto.io.openisms.v1.OperatingSystem.OperatingSystems} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.io.openisms.v1.OperatingSystem.OperatingSystems} value
 * @return {!proto.io.openisms.v1.OperatingSystem} returns this
 */
proto.io.openisms.v1.OperatingSystem.prototype.setOs = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string major_version = 2;
 * @return {string}
 */
proto.io.openisms.v1.OperatingSystem.prototype.getMajorVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.openisms.v1.OperatingSystem} returns this
 */
proto.io.openisms.v1.OperatingSystem.prototype.setMajorVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string full_version = 3;
 * @return {string}
 */
proto.io.openisms.v1.OperatingSystem.prototype.getFullVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.openisms.v1.OperatingSystem} returns this
 */
proto.io.openisms.v1.OperatingSystem.prototype.setFullVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


