// source: io/openisms/api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.io.openisms.v1.SecurityFeatures');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.BoolValue');
goog.require('proto.google.protobuf.Int32Value');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.openisms.v1.SecurityFeatures = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.openisms.v1.SecurityFeatures, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.openisms.v1.SecurityFeatures.displayName = 'proto.io.openisms.v1.SecurityFeatures';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.toObject = function(opt_includeInstance) {
  return proto.io.openisms.v1.SecurityFeatures.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.openisms.v1.SecurityFeatures} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.openisms.v1.SecurityFeatures.toObject = function(includeInstance, msg) {
  var f, obj = {
    activationLock: (f = msg.getActivationLock()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    supervised: (f = msg.getSupervised()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    fileVault: (f = msg.getFileVault()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    fullDiskEncryption: (f = msg.getFullDiskEncryption()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    securePassword: (f = msg.getSecurePassword()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    automaticScreenLock: (f = msg.getAutomaticScreenLock()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    screenLockAfter: (f = msg.getScreenLockAfter()) && proto.google.protobuf.Int32Value.toObject(includeInstance, f),
    firewallEnabled: (f = msg.getFirewallEnabled()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    automaticUpdates: (f = msg.getAutomaticUpdates()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.openisms.v1.SecurityFeatures}
 */
proto.io.openisms.v1.SecurityFeatures.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.openisms.v1.SecurityFeatures;
  return proto.io.openisms.v1.SecurityFeatures.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.openisms.v1.SecurityFeatures} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.openisms.v1.SecurityFeatures}
 */
proto.io.openisms.v1.SecurityFeatures.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setActivationLock(value);
      break;
    case 2:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setSupervised(value);
      break;
    case 3:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setFileVault(value);
      break;
    case 4:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setFullDiskEncryption(value);
      break;
    case 5:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setSecurePassword(value);
      break;
    case 6:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setAutomaticScreenLock(value);
      break;
    case 7:
      var value = new proto.google.protobuf.Int32Value;
      reader.readMessage(value,proto.google.protobuf.Int32Value.deserializeBinaryFromReader);
      msg.setScreenLockAfter(value);
      break;
    case 8:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setFirewallEnabled(value);
      break;
    case 9:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setAutomaticUpdates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.openisms.v1.SecurityFeatures.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.openisms.v1.SecurityFeatures} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.openisms.v1.SecurityFeatures.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivationLock();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getSupervised();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getFileVault();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getFullDiskEncryption();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getSecurePassword();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getAutomaticScreenLock();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getScreenLockAfter();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.google.protobuf.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getFirewallEnabled();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getAutomaticUpdates();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.BoolValue activation_lock = 1;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getActivationLock = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 1));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setActivationLock = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearActivationLock = function() {
  return this.setActivationLock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasActivationLock = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.BoolValue supervised = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getSupervised = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 2));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setSupervised = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearSupervised = function() {
  return this.setSupervised(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasSupervised = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.BoolValue file_vault = 3;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getFileVault = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 3));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setFileVault = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearFileVault = function() {
  return this.setFileVault(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasFileVault = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.BoolValue full_disk_encryption = 4;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getFullDiskEncryption = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 4));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setFullDiskEncryption = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearFullDiskEncryption = function() {
  return this.setFullDiskEncryption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasFullDiskEncryption = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.BoolValue secure_password = 5;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getSecurePassword = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 5));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setSecurePassword = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearSecurePassword = function() {
  return this.setSecurePassword(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasSecurePassword = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.BoolValue automatic_screen_lock = 6;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getAutomaticScreenLock = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 6));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setAutomaticScreenLock = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearAutomaticScreenLock = function() {
  return this.setAutomaticScreenLock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasAutomaticScreenLock = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Int32Value screen_lock_after = 7;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getScreenLockAfter = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Int32Value, 7));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setScreenLockAfter = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearScreenLockAfter = function() {
  return this.setScreenLockAfter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasScreenLockAfter = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.BoolValue firewall_enabled = 8;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getFirewallEnabled = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 8));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setFirewallEnabled = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearFirewallEnabled = function() {
  return this.setFirewallEnabled(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasFirewallEnabled = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.BoolValue automatic_updates = 9;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.getAutomaticUpdates = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 9));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
*/
proto.io.openisms.v1.SecurityFeatures.prototype.setAutomaticUpdates = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.openisms.v1.SecurityFeatures} returns this
 */
proto.io.openisms.v1.SecurityFeatures.prototype.clearAutomaticUpdates = function() {
  return this.setAutomaticUpdates(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.openisms.v1.SecurityFeatures.prototype.hasAutomaticUpdates = function() {
  return jspb.Message.getField(this, 9) != null;
};


